### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by atarkowska** [ome/omero-upload#9]
What is that nice piece of software doing exactly?

**Comment by sbesson** [comment]
Hi @olatarkowska, this library is for uploading files into an OMERO.server as `OriginalFile` objects. In particular, it allows the possibility of uploading files in-place using symlinks similarly to in-place imports.

You can see an example of consumption in https://github.com/IDR/idr0052-walther-condensinmap/blob/master/scripts/upload_and_create_rois.py which uploads TIFF masks as `FileAnnotations` and converts them into ROIs - see https://idr.openmicroscopy.org/webclient/?show=image-5514374.
